

development:
  adapter: postgresql
  database: my_database_development
  username: adilnm
  password: adil1986
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_development
  username: adilnm
  password: adil1986
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_development
  username: adilnm
  password: adil1986
  pool: 5
  timeout: 5000